# Generated by Django 2.0.2 on 2020-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reacted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
