# Generated by Django 2.0.2 on 2020-04-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0003_auto_20200407_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reacted_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
